phonebook/phonebook/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('webapp/', include('webapp.urls', namespace="webapp")),
    path('admin/', admin.site.urls, name='main_admin'),
]

phonebook/webapp/urls.py
from django.urls import path

from . import views

app_name = "webapp"
urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.listContacts, name='index'),
    path('<int:contact_id>', views.listContacts, name='contact_detail'),
    path('groups/', views.groups, name='groups'),
    path('groups/<int:group_id>', views.groups, name='group_detail'),
    path('office/', views.offices, name='offices'),
    path('office/<int:office_id>', views.offices, name='office_detail'),
    path('location/', views.locations, name='locations'),
    path('location/<int:location_id>', views.locations, name='location_detail'),
    path('new/contact', views.new_contact, name='new_contact'),
    path('new/contact/phone/<int:contact_id>', views.new_contact_phone, name='new_contact_phone'),
    path('new/contact/email/<int:contact_id>', views.new_contact_email, name='new_contact_email'),
    path('new/group', views.new_group, name="new_group"),
    path('new/office', views.new_office, name="new_office"),
    path('new/location', views.new_location, name="new_location"),

]

phonebook/webapp/models.py
from django.db import models
from fontawesome_5.fields import IconField

# from django.urls import reverse
# Create your models here.

MAX_ENTRIES = 2

class Settings(models.Model):
    max_entries = models.IntegerField(default=2)
    add_entry = models.BooleanField(default=True)
    add_contact = models.BooleanField(default=True)
    add_group = models.BooleanField(default=True)
    add_office = models.BooleanField(default=True)
    add_location = models.BooleanField(default=True)
    max_item_per_list = models.IntegerField(default=10)
    google_map_link = models.BooleanField(default=True)
    active = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.created_at) + " - " + str(self.active)

    def can_add_location(self):
        return self.add_location

class Location(models.Model):
    name = models.CharField(max_length=256)
    address = models.TextField()
    deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

class Office(models.Model):
    name = models.CharField(max_length=256)
    alias = models.CharField(max_length=64)
    deleted = models.BooleanField(default=False)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

class Group(models.Model):
    name = models.CharField(max_length=256)
    alias = models.CharField(max_length=64)
    deleted = models.BooleanField(default=False)
    office = models.ForeignKey(Office, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

class Contact(models.Model):
    first_name = models.CharField(max_length=128)
    middle_name = models.CharField(max_length=128, null=True, blank=True)
    last_name = models.CharField(max_length=128)
    initials = models.CharField(max_length=4, null=True, blank=True)
    deleted = models.BooleanField(default=False)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    fa = IconField(default="fas,user")  # Fontawesome Icon
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('last_name', 'first_name', 'middle_name')

    def __str__(self):
        return self.name()

    def get_setting(self):
        setting = Settings.objects.get(active=True)
        return setting

    def name(self):
        if not self.middle_name:
            middle_name = " "
        else:
            middle_name = self.middle_name
        name = "{} {} {}".format(self.first_name, middle_name, self.last_name)
        return name

    def getPhones(self):
        return Phone.objects.filter(contact=self.pk).order_by('type')

    def getEmails(self):
        return Email.objects.filter(contact=self.pk).order_by('type')

    def actions_available(self):

        return ""

    def can_add_email(self):
        setting = self.get_setting()
        if setting.add_entry:
            if len(self.getEmails()) < MAX_ENTRIES:
                return True

        return False

    def can_add_phone(self):
        setting = self.get_setting()
        if setting.add_entry:
            if len(self.getPhones()) < MAX_ENTRIES:
                return True

        return False

class TypeContact(models.Model):
    name = models.CharField(max_length=128)
    description = models.CharField(max_length=512)
    deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Email(models.Model):
    account = models.CharField(max_length=256)
    domain = models.CharField(max_length=128, null=True, blank=True)
    deleted = models.BooleanField(default=False)
    type = models.ForeignKey(TypeContact, on_delete=models.CASCADE)
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.account

class Phone(models.Model):
    country_code = models.IntegerField(default=56)
    number = models.CharField(max_length=16)
    annex = models.IntegerField(null=True, blank=True)
    deleted = models.BooleanField(default=False)
    type = models.ForeignKey(TypeContact, on_delete=models.CASCADE)
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        phone_number = "+" + str(self.country_code) + " " + str(self.number)
        return self.contact.name() + " " + phone_number

    def get_country_code(self):
        cc = "+" + str(self.country_code)
        return cc

    def full_number(self):
        if self.number.startswith(self.get_country_code()):
            phone_number = self.number
        else:
            phone_number = self.get_country_code() + " " + str(self.number)
        if self.annex :
            phone_number += " Anexo "+ str(self.annex)
        return phone_number

phonebook/webapp/forms.py
from django import forms
from .models import Contact, Phone, Email, Group, Office, Location

class NewContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('first_name',
                'middle_name',
                'last_name',
                'initials',
                'group',
        )


class NewPhoneForm(forms.ModelForm):
    class Meta:
        model = Phone
        fields = ('country_code', 'number', 'annex', 'type', 'contact')
        widgets = {'contact': forms.HiddenInput()}


class NewEmailForm(forms.ModelForm):
    class Meta:
        model = Email
        fields = ('account', 'type', 'contact')
        widgets = {'account': forms.EmailInput(), 'contact': forms.HiddenInput()}


class NewGroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ('name', 'alias', 'office')


class NewOfficeForm(forms.ModelForm):
    class Meta:
        model = Office
        fields = ('name', 'alias', 'location')


class NewLocationForm(forms.ModelForm):
    class Meta:
        model = Location
        fields = ('name', 'address')

phonebook/webapp/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from django.core.paginator import Paginator

from .forms import NewContactForm, NewPhoneForm, NewEmailForm
from .forms import NewGroupForm, NewOfficeForm, NewLocationForm

from .models import Contact, Group, Office, Location, Settings


def listContacts(request, contact_id=False):
    config = Settings.objects.get(active=True)

    if request.method == "POST":
        criteria = request.POST['criteria']
        contact_list = Contact.objects.filter(
                    Q(first_name__contains=criteria) |
                    Q(middle_name__contains=criteria) |
                    Q(last_name__contains=criteria) |
                    Q(initials__contains=criteria)
        )
    else:
        contact_list = Contact.objects.all()

    page = request.GET.get('page')
    paginator = Paginator(contact_list, config.max_item_per_list)
    contacts = paginator.get_page(page)

    context = {'contacts': contacts, 'can_add': config.add_contact}

    if contact_id:
        context['contact_to_show'] = Contact.objects.get(pk=contact_id)

    return render(request, 'webapp/contact_list.html', context)


def new_contact(request):
    if request.method == "POST":
        form = NewContactForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('webapp:contact_detail', contact_id=post.pk)
    else:
        form = NewContactForm()
        return render(
                    request,
                    'webapp/add_form.html',
                    {'form': form, 'title': "Add Contact"}
        )
    return ""  # This one will never be reached!


def new_contact_phone(request, contact_id):
    if request.method == "POST":
        form = NewPhoneForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('webapp:contact_detail', contact_id=post.contact_id)
    else:
        form = NewPhoneForm(initial={'contact': contact_id})
        return render(
                    request,
                    'webapp/add_form.html',
                    {'form': form, 'title': "Add Phone"}
        )
    return ""  # This one will never be reached!


def new_contact_email(request, contact_id):
    if request.method == "POST":
        form = NewEmailForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('webapp:contact_detail', contact_id=post.contact_id)
    else:
        form = NewEmailForm(initial={'contact': contact_id})
        return render(
                    request,
                    'webapp/add_form.html',
                    {'form': form, 'title': "Add Email"}
        )
    return ""  # This one will never be reached!


def groups(request, group_id=False):
    config = Settings.objects.get(active=True)
    group_list = Group.objects.all()

    page = request.GET.get('page')
    paginator = Paginator(group_list, config.max_item_per_list)
    groups = paginator.get_page(page)
    context = {'groups': groups, 'can_add': config.add_group}

    if group_id:
        context['group_to_show'] = Group.objects.get(pk=group_id)

    return render(request, 'webapp/group_list.html', context)


def new_group(request):
    if request.method == "POST":
        form = NewGroupForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('webapp:group_detail', group_id=post.pk)
    else:
        form = NewGroupForm()
        return render(
                    request,
                    'webapp/add_form.html',
                    {'form': form, 'title': "Add Group"}
        )
    return ""  # This will bring errors


def offices(request, office_id=False):
    config = Settings.objects.get(active=True)
    office_list = Office.objects.all()
    page = request.GET.get('page')
    paginator = Paginator(office_list, config.max_item_per_list)
    offices = paginator.get_page(page)
    context = {'offices': offices, 'can_add': config.add_office}

    if office_id:
        context['office_to_show'] = Office.objects.get(pk=office_id)

    return render(request, 'webapp/office_list.html', context)


def new_office(request):
    if request.method == "POST":
        form = NewOfficeForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('webapp:office_detail', office_id=post.pk)
    else:
        form = NewOfficeForm()
        return render(
                    request,
                    'webapp/add_form.html',
                    {'form': form, 'title': "Add Office"}
        )
    return ""  # This will bring errors


def locations(request, location_id=False):
    config = Settings.objects.get(active=True)
    location_list = Location.objects.all()
    page = request.GET.get('page')
    paginator = Paginator(location_list, config.max_item_per_list)
    locations = paginator.get_page(page)
    context = {'locations': locations, 'can_add': config.add_location}

    if location_id:
        context['location_to_show'] = Location.objects.get(pk=location_id)

    return render(request, 'webapp/location_list.html', context)


def new_location(request):
    if request.method == "POST":
        form = NewLocationForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('webapp:location_detail', location_id=post.pk)
    else:
        form = NewLocationForm()
        return render(
                    request,
                    'webapp/add_form.html',
                    {'form': form, 'title': "Add Location"}
        )
    return ""  # This will bring errors

phonebook/webapp/templates/webapp/add_form.html
{% extends 'webapp/base_forms.html' %}
{% load bootstrap %}

{% block page_title%}
  <h3>
    <i class="fas fa-plus-square">&nbsp;</i>{{ title }}
  </h3>
{% endblock%}

{% block web_forms %}

  {% if form %}

    <form method="POST" class="post-form">
      {% csrf_token %}
      {{ form|bootstrap }}
      {% block cancel_action %}
      <a href="{% url 'webapp:index' %}">
      <button class="btn btn-outline-danger">
        <i class="fas fa-times-circle">&nbsp;</i>Cancel</button>
      </a>
      {% endblock %}
      <button type="submit" class="btn btn-outline-primary">
        <i class="fas fa-save">&nbsp;</i>Save</button>
    </form>

  {% endif %}

{% endblock %}

phonebook/webapp/templates/webapp/base.html
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Just Another Phonebook using Django</title>

  <meta name="description" content="Phonebook App">
  <meta name="description" content="Source code generated using layoutit.com">
  <meta name="author" content="Esteban Osorio Gallardo">

  {# Load fontawesome5 #}
  {% load fontawesome_5 %}
  {% fontawesome_5_static %}

  {# Load Bootstrap #}
  {% load bootstrap4 %}

  {# Load CSS and JavaScript #}
  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}

</head>
<body>
  <div class="container-fluid">
   <div class="row">
   <div class="col-md-1"></div>
   <div class="col-md-10">
     <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-dark bg-dark">
       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" data-_extension-text-contrast="">
         <span class="navbar-toggler-icon"></span>
       </button> <a class="navbar-brand" href="{% url 'webapp:index' %}"><i class="far fa-address-book"></i><!-- BRAND --></a>
       <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
         <ul class="navbar-nav">
           <li class="nav-item">
              <a class="nav-link" href="{% url 'webapp:index' %}"><i class="fas fa-user">&nbsp;</i>Contacts</a>
           </li>
           <li class="nav-item">
              <a class="nav-link" href="{% url 'webapp:groups' %}"><i class="fas fa-users">&nbsp;</i>Groups</a>
           </li>
           <li class="nav-item">
              <a class="nav-link" href="{% url 'webapp:offices' %}"><i class="fas fa-building">&nbsp;</i>Office</a>
           </li>
           <li class="nav-item">
              <a class="nav-link" href="{% url 'webapp:locations' %}"><i class="fas fa-map-marked-alt">&nbsp;</i>Locations</a>
           </li>
           <li class="nav-item">
              <a class="nav-link" href="#"><i class="fas fa-question-circle">&nbsp;</i>Help</a>
           </li>
           <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}"><i class="fas fa-robot">&nbsp;</i>Admin</a>
           </li>
         </ul>
         <form action="{% url 'webapp:index' %}" class="form-inline" method="POST">
           {% csrf_token %}
           <input class="form-control mr-sm-2" name="criteria" type="text">
           <button class="btn btn-primary my-2 my-sm-0" type="submit">
             <i class="fas fa-search">&nbsp;</i>Search
           </button>
         </form>
       </div>
     </nav>
     <div class="row">
       <div class="col-md-4">
         <br>
           {% block page_title %}
            <h3><i class="far fa-address-book"></i>&nbsp;Just another django phonebook</h3>
           {% endblock %}

         <br>
       </div>
       <div class="col-md-4">
         <br>
         <span class="float-right">
           {% block add_new_element%}
             <button type="button" class="btn btn-outline-info">
               <a class="nav-link" href="{% url 'webapp:new_contact' %}">
                 <i class="fas fa-plus-square">&nbsp;</i>New Contact
               </a>
             </button>
           {% endblock %}

         </span>
       </div>
       <div class="col-md-4">

       </div>
     </div>

     <div class="row">
       <div class="col-md-8">

        {# Main list  #}
        {% block main_list %}
          <!-- PUT HERE A CONTACT LIST -->
        {% endblock %}

        </div>
        <div class="col-md-4">

        <p class="text-info">
        {# Info Detail #}
        {% block info_detail %}
          <!-- PUT HERE A CONTACT DETAIL -->
        {% endblock %}
        </p>

        </div>
      </div>
    </div>
    <div class="col-md-1"></div>
  </div>
</div>
</body>
</html>

phonebook/webapp/templates/webapp/base_forms.html
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Just Another Phonebook using Django</title>

  <meta name="description" content="Phonebook App">
  <meta name="description" content="Source code generated using layoutit.com">
  <meta name="author" content="Esteban Osorio Gallardo">

  {# Load fontawesome5 #}
  {% load fontawesome_5 %}
  {% fontawesome_5_static %}

  {# Load Bootstrap #}
  {% load bootstrap4 %}

  {# Load CSS and JavaScript #}
  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}

</head>
<body>
  <div class="container-fluid">
   <div class="row">
   <div class="col-md-1"></div>
   <div class="col-md-10">
     <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-dark bg-dark">

       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" data-_extension-text-contrast="">
         <span class="navbar-toggler-icon"></span>
       </button> <a class="navbar-brand" href="{% url 'webapp:index' %}"><i class="far fa-address-book">&nbsp;</i><!-- BRAND --></a>
       <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
         <ul class="navbar-nav">
           <li class="nav-item">
              <a class="nav-link" href="{% url 'webapp:index' %}"><i class="fas fa-user">&nbsp;</i>Contacts</a>
           </li>
           <li class="nav-item">
              <a class="nav-link" href="{% url 'webapp:groups' %}"><i class="fas fa-users">&nbsp;</i>Groups</a>
           </li>
           <li class="nav-item">
              <a class="nav-link" href="{% url 'webapp:offices' %}"><i class="fas fa-building">&nbsp;</i>Office</a>
           </li>
           <li class="nav-item">
              <a class="nav-link" href="{% url 'webapp:locations' %}"><i class="fas fa-map-marked-alt">&nbsp;</i>Locations</a>
           </li>
           <li class="nav-item">
              <a class="nav-link" href="#"><i class="fas fa-question-circle">&nbsp;</i>Help</a>
           </li>
           <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}"><i class="fas fa-robot">&nbsp;</i>Admin</a>
           </li>
         </ul>
       </div>
     </nav>
     <br><h3>
       {% block page_title %}
        <i class="far fa-address-book"></i>&nbsp;Just another django phonebook
       {% endblock %}
     </h3><br>
     <div class="row">
       <div class="col-md-12">

        {# Contact list  #}
        {% block web_forms %}
          <!-- PUT FORMS HERE -->
        {% endblock %}

        </div>

      </div>
    </div>
    <div class="col-md-1"></div>
  </div>
</div>

</body>
</html>

phonebook/webapp/templates/webapp/contact.html
{% if contact %}
  contact.id <br>
  contact.fullName
{% else %}
  No Contact to show
{% endif %}

phonebook/webapp/templates/webapp/contact_list.html
{% extends 'webapp/base.html' %}

{% block page_title %}
  <h3>
    <i class="fas fa-user">&nbsp;</i>Contacts
  </h3>
{% endblock %}

{% block add_new_element %}
  {% if can_add %}

    <button type="button" class="btn btn-outline-info">
      <a class="nav-link" href="{% url 'webapp:new_contact' %}">
        <i class="fas fa-plus-square">&nbsp;</i>New Contact
      </a>
    </button>

  {% endif %}

{% endblock %}

{% block main_list %}

  {% if contacts %}
  <table class="table table-sm table-striped">
    <thead>
      <tr>
        <th>
          Last Name
        </th>
        <th>
          Name
        </th>
        <th>
          Middle Name
        </th>
        <th>
          Group
        </th>
        <th>
          Office
        </th>
        <th class="text-center">Actions</th>
    </thead>
    <tbody>

    {% for contact in contacts %}

      <tr>
        <td> {{ contact.last_name}} </td>
        <td> {{ contact.first_name}} </td>
        <td>
          {% if contact.middle_name %}
           {{ contact.middle_name}}
          {% else %}
            &nbsp;
          {% endif %}
        </td>
        <td> {{ contact.group.name }} </td>
        <td> {{ contact.group.office.name }} </td>
        <td class="text-center"> {{ contact.actions_available }}
            <a href="{{ contact.pk }}"><i class="fas fa-eye"></i></a>
            <!-- <i class="fas fa-pencil-alt"></i>
            <i class="fas fa-trash"></i> -->
            <!-- vCard downloader?  <i class="fas fa-id-card"></i> -->
        </td>
      </tr>

      {# OTHER CLASS FOR EACH TR #}
      {# table-active, table-success, table-warning, table-danger #}
    {% endfor %}

    </tbody>
    </table>

    <!-- PAGINATOR -->
    <div class="pagination">
      <span class="step-links">
          {% if contacts.has_previous %}
              <a href="?page=1">
                <i class="fas fa-angle-double-left"></i>
              </a>
              <a href="?page={{ contacts.previous_page_number }}">
                <i class="fas fa-angle-left"></i>
              </a>
          {% endif %}

          <span class="current">
              {{ contacts.number }} of {{ contacts.paginator.num_pages }}
          </span>

          {% if contacts.has_next %}
              <a href="?page={{ contacts.next_page_number }}">
                <i class="fas fa-angle-right"></i>
              </a>
              <a href="?page={{ contacts.paginator.num_pages }}">
                <i class="fas fa-angle-double-right"></i>
              </a>
          {% endif %}
      </span>
    </div>|
    <!-- END PAGINATOR -->

  {% else %}

    <h5>
      <i class="far fa-grin-beam-sweat">&nbsp;</i>
      No Contacts found!
    </h5>

  {% endif %}

{% endblock %}

{% block info_detail %}

  {% if contact_to_show %}

  <p>
    <h5 class="text-info">
      {{contact_to_show.fa.as_html}}
      {{ contact_to_show.name }}
    </h5>
    <p>
    {{ contact_to_show.group }} - {{ contact_to_show.group.office }} <br>
    <i class="fas fa-map-marker-alt">&nbsp;</i>{{ contact_to_show.group.office.location }}
    </p>
    <p>
    {% for phone in contact_to_show.getPhones %}
      <i class="fas fa-phone">&nbsp;</i> {{ phone.full_number }}<br>

    {% endfor %}
    </p>
    <p>
    {% for email in contact_to_show.getEmails %}
      <i class="fas fa-at">&nbsp;</i> {{ email }}<br>
    {% endfor %}
    </p>
    {% if contact_to_show.can_add_phone %}
    <a href="{% url 'webapp:new_contact_phone' contact_id=contact_to_show.pk %}">
      <i class="fas fa-phone-square">&nbsp</i>Add Phone
    </a>
    {% endif %}
    {% if contact_to_show.can_add_email %}
    <a href="{% url 'webapp:new_contact_email' contact_id=contact_to_show.pk %}">
      <i class="fas fa-envelope-square">&nbsp</i>Add Email
    </a>
    {% endif %}
  </p>

  {% else %}

    <i class="far fa-meh-rolling-eyes">&nbsp;</i>No contact to display.
    <br>
    <p>Choose a contact to display more information.</p>
  {% endif %}

{% endblock %}

phonebook/webapp/templates/webapp/help.html
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Just Another Phonebook using Django</title>

  <meta name="description" content="Phonebook App">
  <meta name="description" content="Source code generated using layoutit.com">
  <meta name="author" content="Esteban Osorio Gallardo">

  {# Load fontawesome5 #}
  {% load fontawesome_5 %}
  {% fontawesome_5_static %}

  {# Load Bootstrap #}
  {% load bootstrap4 %}

  {# Load CSS and JavaScript #}
  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}

</head>
<body>
  <div class="container-fluid">
   <div class="row">
   <div class="col-md-1"></div>
   <div class="col-md-10">
     <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-dark bg-dark">
       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" data-_extension-text-contrast="">
         <span class="navbar-toggler-icon"></span>
       </button> <a class="navbar-brand" href="{% url 'webapp:index' %}"><i class="far fa-address-book"></i><!-- BRAND --></a>
       <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
         <ul class="navbar-nav">
           <li class="nav-item">
              <a class="nav-link" href="{% url 'webapp:index' %}"><i class="fas fa-user">&nbsp;</i>Contacts</a>
           </li>
           <li class="nav-item">
              <a class="nav-link" href="{% url 'webapp:groups' %}"><i class="fas fa-users">&nbsp;</i>Groups</a>
           </li>
           <li class="nav-item">
              <a class="nav-link" href="{% url 'webapp:offices' %}"><i class="fas fa-building">&nbsp;</i>Office</a>
           </li>
           <li class="nav-item">
              <a class="nav-link" href="{% url 'webapp:locations' %}"><i class="fas fa-map-marked-alt">&nbsp;</i>Locations</a>
           </li>
           <li class="nav-item">
              <a class="nav-link" href="#"><i class="fas fa-question-circle">&nbsp;</i>Help</a>
           </li>
           <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}"><i class="fas fa-robot">&nbsp;</i>Admin</a>
           </li>
         </ul>
         <form action="{% url 'webapp:index' %}" class="form-inline" method="POST">
           {% csrf_token %}
           <input class="form-control mr-sm-2" name="criteria" type="text">
           <button class="btn btn-primary my-2 my-sm-0" type="submit">
             <i class="fas fa-search">&nbsp;</i>Search
           </button>
         </form>
       </div>
     </nav>
     <div class="row">
       <div class="col-md-4">
         <br>
           {% block page_title %}
            <h3><i class="far fa-address-book"></i>&nbsp;Just another django phonebook</h3>
           {% endblock %}

         <br>
       </div>
       <div class="col-md-4">
         <br>
         <span class="float-right">
           <button type="button" class="btn btn-outline-info">
             {% block add_new_element%}
               <a class="nav-link" href="{% url 'webapp:new_contact' %}">
                 <i class="fas fa-plus-square">&nbsp;</i>New Contact
               </a>
             {% endblock %}
           </button>
         </span>
       </div>
       <div class="col-md-4">

       </div>
     </div>

     <div class="row">
       <div class="col-md-8">

        {# Main list  #}
        {% block main_list %}
          <!-- PUT HERE A CONTACT LIST -->
        {% endblock %}

        </div>
        <div class="col-md-4">

        <p class="text-info">
        {# Info Detail #}
        {% block info_detail %}
          <!-- PUT HERE A CONTACT DETAIL -->
        {% endblock %}
        </p>

        </div>
      </div>
    </div>
    <div class="col-md-1"></div>
  </div>
</div>
</body>
</html>